# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'git@gitlab.alibaba-inc.com:YTBase/YTSpec.git'

target 'PWNote' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PWNote
  pod 'Masory'
  pod 'ReactiveCocoa'

end
