# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# https://blog.csdn.net/guo405240393/article/details/80319520
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'PWNote' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PWNote
  pod 'Masory'
  pod 'ReactiveCocoa'

end
