/**
 * Auto-generated by `./install` on 12/06/2018
 * Copyright © 2017 galen. App rights reserved.
 */

#import <UIKit/UIKit.h>
#import "AMButtonFactory.h"

// 对应html文件保存在工程根目录 Iconfont Doc 目录下

@interface AMIconfont : NSObject

+ (UIFont *)fontWithSize:(CGFloat)size;

+ (NSString *)iconFromSymbol:(NSString *)symbol;

+ (NSString *)iconSquarecheckfill __deprecated_msg("Use XIconSquarecheckfill instead.");
+ (NSString *)iconSquare __deprecated_msg("Use XIconSquare instead.");
+ (NSString *)iconCategory __deprecated_msg("Use XIconCategory instead.");
+ (NSString *)iconSmile __deprecated_msg("Use XIconSmile instead.");
+ (NSString *)iconShezhi __deprecated_msg("Use XIconShezhi instead.");
+ (NSString *)iconShouye __deprecated_msg("Use XIconShouye instead.");

@end

UIKIT_EXTERN NSString *const XIconSquarecheckfill;
UIKIT_EXTERN NSString *const XIconSquare;
UIKIT_EXTERN NSString *const XIconCategory;
UIKIT_EXTERN NSString *const XIconSmile;
UIKIT_EXTERN NSString *const XIconShezhi;
UIKIT_EXTERN NSString *const XIconShouye;

/**
 根据符号名获取 IconFont Unicode

 @param symbol 符号名
 @return 找不到返回 nil, 否则返回相应的 unicode
 */
UIKIT_STATIC_INLINE NSString *XIconFromSymbol(NSString *symbol) {
    return [AMIconfont iconFromSymbol:symbol];
}
