/**
 * Auto-generated by `./install` on 01/11/2019
 * Copyright © 2017 galen. App rights reserved.
 */

#import <UIKit/UIKit.h>
#import "AMButtonFactory.h"

// 对应html文件保存在工程根目录 Iconfont Doc 目录下

@interface AMIconfont : NSObject

+ (UIFont *)fontWithSize:(CGFloat)size;

+ (NSString *)iconFromSymbol:(NSString *)symbol;

+ (NSString *)iconSquarecheckfill __deprecated_msg("Use XIconSquarecheckfill instead.");
+ (NSString *)iconSquare __deprecated_msg("Use XIconSquare instead.");
+ (NSString *)iconSquarecheck __deprecated_msg("Use XIconSquarecheck instead.");
+ (NSString *)iconBack __deprecated_msg("Use XIconBack instead.");
+ (NSString *)iconCategory __deprecated_msg("Use XIconCategory instead.");
+ (NSString *)iconDelete __deprecated_msg("Use XIconDelete instead.");
+ (NSString *)iconEdit __deprecated_msg("Use XIconEdit instead.");
+ (NSString *)iconFavorite __deprecated_msg("Use XIconFavorite instead.");
+ (NSString *)iconPic __deprecated_msg("Use XIconPic instead.");
+ (NSString *)iconRefresh __deprecated_msg("Use XIconRefresh instead.");
+ (NSString *)iconSearch __deprecated_msg("Use XIconSearch instead.");
+ (NSString *)iconSmile __deprecated_msg("Use XIconSmile instead.");
+ (NSString *)iconAdd __deprecated_msg("Use XIconAdd instead.");
+ (NSString *)iconShezhi __deprecated_msg("Use XIconShezhi instead.");
+ (NSString *)iconShouye __deprecated_msg("Use XIconShouye instead.");
+ (NSString *)iconScanning __deprecated_msg("Use XIconScanning instead.");
+ (NSString *)iconSkip __deprecated_msg("Use XIconSkip instead.");
+ (NSString *)iconColor __deprecated_msg("Use XIconColor instead.");
+ (NSString *)iconColorFilling __deprecated_msg("Use XIconColorFilling instead.");
+ (NSString *)iconCalculator __deprecated_msg("Use XIconCalculator instead.");
+ (NSString *)iconTaskManagement __deprecated_msg("Use XIconTaskManagement instead.");
+ (NSString *)iconPassword __deprecated_msg("Use XIconPassword instead.");
+ (NSString *)iconCamera __deprecated_msg("Use XIconCamera instead.");
+ (NSString *)iconHelpFill __deprecated_msg("Use XIconHelpFill instead.");
+ (NSString *)iconAddAccount __deprecated_msg("Use XIconAddAccount instead.");
+ (NSString *)iconIconMorentouxiang __deprecated_msg("Use XIconIconMorentouxiang instead.");

@end

UIKIT_EXTERN NSString *const XIconSquarecheckfill;
UIKIT_EXTERN NSString *const XIconSquare;
UIKIT_EXTERN NSString *const XIconSquarecheck;
UIKIT_EXTERN NSString *const XIconBack;
UIKIT_EXTERN NSString *const XIconCategory;
UIKIT_EXTERN NSString *const XIconDelete;
UIKIT_EXTERN NSString *const XIconEdit;
UIKIT_EXTERN NSString *const XIconFavorite;
UIKIT_EXTERN NSString *const XIconPic;
UIKIT_EXTERN NSString *const XIconRefresh;
UIKIT_EXTERN NSString *const XIconSearch;
UIKIT_EXTERN NSString *const XIconSmile;
UIKIT_EXTERN NSString *const XIconAdd;
UIKIT_EXTERN NSString *const XIconShezhi;
UIKIT_EXTERN NSString *const XIconShouye;
UIKIT_EXTERN NSString *const XIconScanning;
UIKIT_EXTERN NSString *const XIconSkip;
UIKIT_EXTERN NSString *const XIconColor;
UIKIT_EXTERN NSString *const XIconColorFilling;
UIKIT_EXTERN NSString *const XIconCalculator;
UIKIT_EXTERN NSString *const XIconTaskManagement;
UIKIT_EXTERN NSString *const XIconPassword;
UIKIT_EXTERN NSString *const XIconCamera;
UIKIT_EXTERN NSString *const XIconHelpFill;
UIKIT_EXTERN NSString *const XIconAddAccount;
UIKIT_EXTERN NSString *const XIconIconMorentouxiang;

/**
 根据符号名获取 IconFont Unicode

 @param symbol 符号名
 @return 找不到返回 nil, 否则返回相应的 unicode
 */
UIKIT_STATIC_INLINE NSString *XIconFromSymbol(NSString *symbol) {
    return [AMIconfont iconFromSymbol:symbol];
}
