/**
 * Auto-generated by `./install` on 01/08/2019
 * Copyright © 2017 galen. App rights reserved.
 */

#import "AMIconfont.h"

NSString *const XIconSquarecheckfill = @"\U0000e6d4";
NSString *const XIconSquare = @"\U0000e6d5";
NSString *const XIconSquarecheck = @"\U0000e6d6";
NSString *const XIconBack = @"\U0000e697";
NSString *const XIconCategory = @"\U0000e699";
NSString *const XIconDelete = @"\U0000e69d";
NSString *const XIconEdit = @"\U0000e69e";
NSString *const XIconFavorite = @"\U0000e6a0";
NSString *const XIconPic = @"\U0000e6a8";
NSString *const XIconSearch = @"\U0000e6ac";
NSString *const XIconSmile = @"\U0000e6af";
NSString *const XIconShezhi = @"\U0000e62a";
NSString *const XIconShouye = @"\U0000e62d";
NSString *const XIconScanning = @"\U0000e6ec";
NSString *const XIconSkip = @"\U0000e718";
NSString *const XIconColor = @"\U0000e760";
NSString *const XIconColorFilling = @"\U0000e7cd";
NSString *const XIconCalculator = @"\U0000e812";
NSString *const XIconTaskManagement = @"\U0000e829";
NSString *const XIconPassword = @"\U0000e82b";
NSString *const XIconCamera = @"\U0000e86e";
NSString *const XIconHelpFill = @"\U0000e87a";
NSString *const XIconAddAccount = @"\U0000e87b";
NSString *const XIconIconMorentouxiang = @"\U0000e613";

@implementation AMIconfont

- (id)init {
  NSAssert(false, @"This class cannot be initialized. Never do it!");
  return nil;
}

+ (UIFont *)fontWithSize:(CGFloat)size {
  return [UIFont fontWithName:@"iconfont" size:size];
}

+ (NSString *)iconFromSymbol:(NSString *)symbol {
  if (symbol == nil) return nil;

  static NSDictionary *symbolIcons = nil;
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    symbolIcons = @{
      @"squarecheckfill": XIconSquarecheckfill,
      @"square": XIconSquare,
      @"squarecheck": XIconSquarecheck,
      @"back": XIconBack,
      @"category": XIconCategory,
      @"delete": XIconDelete,
      @"edit": XIconEdit,
      @"favorite": XIconFavorite,
      @"pic": XIconPic,
      @"search": XIconSearch,
      @"smile": XIconSmile,
      @"shezhi": XIconShezhi,
      @"shouye": XIconShouye,
      @"scanning": XIconScanning,
      @"skip": XIconSkip,
      @"color": XIconColor,
      @"colorfilling": XIconColorFilling,
      @"Calculator": XIconCalculator,
      @"taskmanagement": XIconTaskManagement,
      @"password": XIconPassword,
      @"camera": XIconCamera,
      @"helpfill": XIconHelpFill,
      @"addaccount": XIconAddAccount,
      @"Iconmorentouxiang": XIconIconMorentouxiang,
    };
  });
  return symbolIcons[symbol];
}

+ (NSString *)iconSquarecheckfill { return XIconSquarecheckfill; }
+ (NSString *)iconSquare { return XIconSquare; }
+ (NSString *)iconSquarecheck { return XIconSquarecheck; }
+ (NSString *)iconBack { return XIconBack; }
+ (NSString *)iconCategory { return XIconCategory; }
+ (NSString *)iconDelete { return XIconDelete; }
+ (NSString *)iconEdit { return XIconEdit; }
+ (NSString *)iconFavorite { return XIconFavorite; }
+ (NSString *)iconPic { return XIconPic; }
+ (NSString *)iconSearch { return XIconSearch; }
+ (NSString *)iconSmile { return XIconSmile; }
+ (NSString *)iconShezhi { return XIconShezhi; }
+ (NSString *)iconShouye { return XIconShouye; }
+ (NSString *)iconScanning { return XIconScanning; }
+ (NSString *)iconSkip { return XIconSkip; }
+ (NSString *)iconColor { return XIconColor; }
+ (NSString *)iconColorFilling { return XIconColorFilling; }
+ (NSString *)iconCalculator { return XIconCalculator; }
+ (NSString *)iconTaskManagement { return XIconTaskManagement; }
+ (NSString *)iconPassword { return XIconPassword; }
+ (NSString *)iconCamera { return XIconCamera; }
+ (NSString *)iconHelpFill { return XIconHelpFill; }
+ (NSString *)iconAddAccount { return XIconAddAccount; }
+ (NSString *)iconIconMorentouxiang { return XIconIconMorentouxiang; }

@end
