/**
 * Auto-generated by `./install` on 12/06/2018
 * Copyright © 2017 galen. App rights reserved.
 */

#import "AMIconfont.h"

NSString *const XIconSquarecheckfill = @"\U0000e6d4";
NSString *const XIconSquare = @"\U0000e6d5";
NSString *const XIconCategory = @"\U0000e699";
NSString *const XIconSmile = @"\U0000e6af";
NSString *const XIconShezhi = @"\U0000e62a";
NSString *const XIconShouye = @"\U0000e62d";

@implementation AMIconfont

- (id)init {
  NSAssert(false, @"This class cannot be initialized. Never do it!");
  return nil;
}

+ (UIFont *)fontWithSize:(CGFloat)size {
  return [UIFont fontWithName:@"iconfont" size:size];
}

+ (NSString *)iconFromSymbol:(NSString *)symbol {
  if (symbol == nil) return nil;

  static NSDictionary *symbolIcons = nil;
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    symbolIcons = @{
      @"squarecheckfill": XIconSquarecheckfill,
      @"square": XIconSquare,
      @"category": XIconCategory,
      @"smile": XIconSmile,
      @"shezhi": XIconShezhi,
      @"shouye": XIconShouye,
    };
  });
  return symbolIcons[symbol];
}

+ (NSString *)iconSquarecheckfill { return XIconSquarecheckfill; }
+ (NSString *)iconSquare { return XIconSquare; }
+ (NSString *)iconCategory { return XIconCategory; }
+ (NSString *)iconSmile { return XIconSmile; }
+ (NSString *)iconShezhi { return XIconShezhi; }
+ (NSString *)iconShouye { return XIconShouye; }

@end