/**
 * Auto-generated by `./install` on 12/06/2018
 * Copyright © 2017 galen. App rights reserved.
 */

'use strict'
export const iconSquarecheckfill = e6d4;
export const iconSquare = e6d5;
export const iconCategory = e699;
export const iconSmile = e6af;
export const iconShezhi = e62a;
export const iconShouye = e62d;
