/**
 * Auto-generated by `./install` on 01/09/2019
 * Copyright © 2017 galen. App rights reserved.
 */

'use strict'
export const iconSquarecheckfill = e6d4;
export const iconSquare = e6d5;
export const iconSquarecheck = e6d6;
export const iconBack = e697;
export const iconCategory = e699;
export const iconDelete = e69d;
export const iconEdit = e69e;
export const iconFavorite = e6a0;
export const iconPic = e6a8;
export const iconSearch = e6ac;
export const iconSmile = e6af;
export const iconAdd = e6b9;
export const iconShezhi = e62a;
export const iconShouye = e62d;
export const iconScanning = e6ec;
export const iconSkip = e718;
export const iconColor = e760;
export const iconColorFilling = e7cd;
export const iconCalculator = e812;
export const iconTaskManagement = e829;
export const iconPassword = e82b;
export const iconCamera = e86e;
export const iconHelpFill = e87a;
export const iconAddAccount = e87b;
export const iconIconMorentouxiang = e613;
